bak - neovim

diff --git a/plugged/vimspector/run_tests b/plugged/vimspector/run_tests
--- a/plugged/vimspector/run_tests
+++ b/plugged/vimspector/run_tests
@@ -19,6 +19,8 @@ VIM_EXE='vim'
 SCREENCOLS=160
 SCREENROWS=48
 ASCIINEMA="python3 -m asciinema"
+TEST_UNTIL_FAILURE=0
+NO_QUIT_ON_FAIL=0
 
 
 # 1 is stdout
@@ -31,6 +33,10 @@ while [ -n "$1" ]; do
       BASEDIR=$(AbsDirOf "$1")
       shift
       ;;
+    "--until-failure")
+      shift
+      TEST_UNTIL_FAILURE=1
+      ;;
     "--install")
       INSTALL=1
       shift
@@ -42,6 +48,10 @@ while [ -n "$1" ]; do
       ;;
     "--update"|"--upgrade")
       UPDATE=1
+      shift
+      ;;
+    "--no-quit-on-fail")
+      NO_QUIT_ON_FAIL=1
       shift
       ;;
     "--report")
@@ -119,10 +129,25 @@ VERSION_OPTIONS=$([ "$IS_NVIM" -ne 0 ] && echo '--headless' || echo '--not-a-ter
 
 RUN_VIM="${VIM_EXE} -N --clean ${VERSION_OPTIONS}"
 
+if which timeout >/dev/null 2>&1; then
+  TIMEOUT_SCRIPT="timeout --verbose --foreground --kill-after 7m 5m"
+else
+  TIMEOUT_SCRIPT=""
+  echo "WARNING: No timeout found, not using timeout"
+fi
+
+# Check that vim's python support actual works, else we can't run tests
+if ! ${TIMEOUT_SCRIPT} ${RUN_VIM} --cmd "py3 import vim; vim.command( 'qa!' )" --cmd "cquit!"; then
+  echo "Vim's python support doesn't work. Cannot run tests" >&2
+  exit 1
+else
+  echo "Vim's python support works. Let's go..."
+fi
+
 # There seems to be a race condition with the way asciinema sets the pty size.
 # It does fork() then if is_child: execvpe(...) else: set_pty_size(). This means
 # the child might read the pty size before it's set. So we use a 1s sleepy.
-RUN_TEST="sleep 1 && ${RUN_VIM} -S lib/run_test.vim"
+RUN_TEST="sleep 1 && ${TIMEOUT_SCRIPT} ${RUN_VIM} -S lib/run_test.vim"
 
 # We use fd 3 for vim's output. Send it to stdout if not already redirected
 # Note: can't use ${out_fd} in a redirect because redirects happen before
@@ -133,7 +158,7 @@ fi
 
 # Basic pre-flight check that vim and python work
 # ffs neovim https://github.com/neovim/neovim/issues/14438
-if ${RUN_VIM} -u support/test_python3.vim .fail; then
+if ${TIMEOUT_SCRIPT} ${RUN_VIM} -u support/test_python3.vim .fail; then
   rm -f .fail
   echo "$VIM_EXE appears to have working python3 support. Let's go..."
 else
@@ -198,11 +223,17 @@ if [ "$INSTALL" = "1" ] || [ "$INSTALL" = "script" ]; then
   fi
 fi
 
+QUIT_ON_FAIL=(-c 'autocmd User VimspectorInstallFailed cquit!')
+
+if [ "$NO_QUIT_ON_FAIL" -eq 1 ]; then
+  QUIT_ON_FAIL=()
+fi
+
 if [ "$INSTALL" = "1" ] || [ "$INSTALL" = "vim" ]; then
   if ! $RUN_VIM -u ${HOMEDIR}/tests/vimrc \
                --cmd "${BASEDIR_CMD}" \
                -c 'autocmd User VimspectorInstallSuccess qa!' \
-               -c 'autocmd User VimspectorInstallFailed cquit!' \
+               "${QUIT_ON_FAIL[@]}" \
                -c "VimspectorInstall --all netcoredbg vscode-js-debug"; then
     echo "Vim installation reported errors" >&2
     exit 1
@@ -213,7 +244,7 @@ if [ "$UPDATE" = "1" ]; then
   if ! $RUN_VIM -u ${HOMEDIR}/tests/vimrc \
                --cmd "${BASEDIR_CMD}" \
                -c 'autocmd User VimspectorInstallSuccess qa!' \
-               -c 'autocmd User VimspectorInstallFailed cquit!' \
+               "${QUIT_ON_FAIL[@]}" \
                -c "VimspectorUpdate"; then
     echo "Vim update reported errors" >&2
     exit 1
@@ -249,72 +280,80 @@ if [ -z "$TESTS" ]; then
   TESTS=${TESTDIR}/*.test.vim
 fi
 
-for t in ${TESTS}; do
-  # split on : into fileName and testName
-  IFS=: read -s tt T <<< "$t"
+while true; do
+  for t in ${TESTS}; do
+    # split on : into fileName and testName
+    IFS=: read -s tt T <<< "$t"
 
-  # Resolve into absolute path ($tt) and test file name ($t)
-  if [ -f "$tt" ]; then
-    tt=$(readlink -f "$tt")
-    t=$(basename "$tt")
-  elif [ -f "$TESTDIR/$tt" ]; then
-    t=$tt
-    tt=$TESTDIR/$t
-  else
-    echo "%ERROR: Unable to find a test named $tt ($t) in $TESTDIR"
-    RESULT=1
-    break
-  fi
-
-  echo ""
-  echo "%RUN: $t ($tt)"
-
-  TESTLOGDIR=${BASEDIR}/tests/logs/$t
-
-  pushd ${TESTDIR} > /dev/null
-    RUN="${RUN_TEST} --cmd \"${BASEDIR_CMD}\" \
-                     --cmd 'au SwapExists * let v:swapchoice = \"e\"'\
-                     $tt $T"
-
-    if ${ASCIINEMA} rec -q --cols $SCREENCOLS --rows $SCREENROWS --overwrite --command "${RUN}" $t.cast >&3 && [ -f $t.res ];  then
-      echo "%PASS: $t PASSED"
+    # Resolve into absolute path ($tt) and test file name ($t)
+    if [ -f "$tt" ]; then
+      tt=$(readlink -f "$tt")
+      t=$(basename "$tt")
+    elif [ -f "$TESTDIR/$tt" ]; then
+      t=$tt
+      tt=$TESTDIR/$t
     else
-      echo "%FAIL: $t FAILED - see $TESTLOGDIR"
+      echo "%ERROR: Unable to find a test named $tt ($t) in $TESTDIR"
       RESULT=1
+      break
     fi
 
-    rm -rf $TESTLOGDIR
-    mkdir -p $TESTLOGDIR
-    ${RUN_VIM} --version > ${TESTLOGDIR}/vimversion
-    if [ "$VIMSPECTOR_TEST_STDOUT" = "messages" ]; then
-      if [ -f messages ]; then
-        echo "%MESSAGES"
-        cat messages
-        echo "%END"
+    echo ""
+    echo "%RUN: $t ($tt)"
+
+    TESTLOGDIR=${BASEDIR}/tests/logs/$t
+
+    pushd ${TESTDIR} > /dev/null
+      RUN="${RUN_TEST} --cmd \"${BASEDIR_CMD}\" \
+                       --cmd 'au SwapExists * let v:swapchoice = \"e\"'\
+                       $tt $T"
+
+      if ${ASCIINEMA} rec -q --cols $SCREENCOLS --rows $SCREENROWS --overwrite --command "${RUN}" $t.cast >&3 && [ -f $t.res ];  then
+        echo "%PASS: $t PASSED"
       else
-        echo "%MESSAGES"
-        echo "No messages found"
-        echo "%END"
+        echo "%FAIL: $t FAILED - see $TESTLOGDIR"
+        RESULT=1
       fi
-    fi
 
-    mv $t.cast $TESTLOGDIR
-    for l in messages debuglog test.log *.testlog; do
-      # In CI we can't view the output files, so we just have to cat them
-      if [ -f $l ]; then
-        if [ "$VIMSPECTOR_TEST_STDOUT" = "all" ]; then
-          echo ""
-          echo ""
-          echo "*** START: $l ***"
-          cat $l
-          echo "*** END: $l ***"
+      rm -rf $TESTLOGDIR
+      mkdir -p $TESTLOGDIR
+      ${RUN_VIM} --version > ${TESTLOGDIR}/vimversion
+      if [ "$VIMSPECTOR_TEST_STDOUT" = "messages" ]; then
+        if [ -f messages ]; then
+          echo "%MESSAGES"
+          cat messages
+          echo "%END"
+        else
+          echo "%MESSAGES"
+          echo "No messages found"
+          echo "%END"
         fi
-        mv $l $TESTLOGDIR
       fi
-    done
 
-    rm -f $t.res
-  popd > /dev/null
+      mv $t.cast $TESTLOGDIR
+      for l in messages debuglog test.log *.testlog; do
+        # In CI we can't view the output files, so we just have to cat them
+        if [ -f $l ]; then
+          if [ "$VIMSPECTOR_TEST_STDOUT" = "all" ]; then
+            echo ""
+            echo ""
+            echo "*** START: $l ***"
+            cat $l
+            echo "*** END: $l ***"
+          fi
+          mv $l $TESTLOGDIR
+        fi
+      done
+
+      rm -f $t.res
+    popd > /dev/null
+  done
+
+  if [ $TEST_UNTIL_FAILURE -eq 1 ] && [ $RESULT -eq 0 ]; then
+    echo "All tests passed. Running again."
+    continue
+  fi
+  break
 done
 
 # close out_fd if it's not stdout/stderr/
